name: Deploy to EC2
on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - backend-event

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p ~/srv/ubuntu

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: ~/srv/ubuntu/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}
      
      - name: executing remote ssh commands using password 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu 
          key: ${{ secrets.KEY }}
          script: |
            sh ~/srv/ubuntu/deploy.sh
            touch ~/srv/ubuntu/.env
            echo "${{ secrets.ENV }}" >> ~/srv/ubuntu/.env
            echo "start docker-compose up: ubuntu"
            sudo docker-compose -f ~/srv/ubuntu/docker-compose.yml pull
            sudo docker-compose -f ~/srv/ubuntu/docker-compose.yml --env-file ~/srv/ubuntu/.env up --build -d
